export default [
  {
    id: 1,
    name: "micheal john",
    pickUpLocation: "head office lagos",
    DropOffLocation: "beside mountain of fire Ajah",
  },
  {
    id: 2,
    name: "peace matthew",
    pickUpLocation: "head office lagos",
    DropOffLocation: "beside mobil filling station epe",
  },
  {
    id: 3,
    name: "bobby madu",
    pickUpLocation: "Benin branch office",
    DropOffLocation: "crown estate airport road benin",
  },
  {
    id: 4,
    name: "yusuf musa",
    pickUpLocation: "Kano branch office",
    DropOffLocation: "babayaro junction gate layi Kano",
  },
  {
    id: 5,
    name: "rebecca olawole",
    pickUpLocation: "Ogun branch office",
    DropOffLocation: "no 22 ibadan way sagamu ogun",
  },
  {
    id: 6,
    name: "kenechukwu uzor",
    pickUpLocation: "Enugu branch office",
    DropOffLocation: "business layout udah enugu",
  },
  {
    id: 7,
    name: "magdalene etuk",
    pickUpLocation: "Uyo branch office",
    DropOffLocation: "25th anniversary estate uyo Akwa ibom",
  },
  {
    id: 8,
    name: "patrick joshua",
    pickUpLocation: "Rivers branch office",
    DropOffLocation: "rumuokoro junction rivers",
  },
  {
    id: 9,
    name: "habibat yunusa",
    pickUpLocation: "Niger branch office",
    DropOffLocation: "plot 559 new bussa Niger state",
  },
  {
    id: 10,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 11,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 12,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 13,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 14,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 15,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 16,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 17,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 18,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 19,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 20,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 21,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 22,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 23,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 24,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 25,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
  {
    id: 26,
    name: "ebuka john",
    pickUpLocation: "Delta branch office",
    DropOffLocation: "ring road benin edo",
  },
];
